name       : kdocker 
version    : 5.2
release    : 1
source     :
    - https://github.com/user-none/KDocker/archive/5.2.tar.gz : ffcb11ac0cf50ae80a35e000b7a7470259e624511d1281579386a9cb68935cba
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : KDocker will help you dock any application in the system tray.
description: |
    KDocker will help you dock any application in the system tray.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - pkgconfig(xmu)
    - pkgconfig(xpm)
setup      : |
    sed -i 's|/etc/bash_completion.d|/usr/share/bash-completion/completions|' kdocker.pro
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir 